LINSPACE

In [1]:
import numpy
array43 = numpy.linspace(4,23,43)
print(array43[5])

6.2619047619


ARREY DIMENSIONS

In [2]:
ones_array = numpy.ones( (5,17) )
zeros_array = numpy.zeros( ones_array.shape )
print(zeros_array)

[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]


ARRAY TRIGONOMETRY

In [3]:
p = 7.0
r= numpy.array([11.2, 4.7, 6.6])
from math import sin
for i in r : print(sin(p/i)**3)

0.20030150930292323
0.9900910096418035
0.6645423764180451


In [5]:
import numpy 
from matplotlib import pyplot
%matplotlib inline

T = 5.0
dt = 0.1
N = int(T/dt)+1
t = numpy.linspace(0.0, T, N)

print(t)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1.   1.1  1.2  1.3  1.4
  1.5  1.6  1.7  1.8  1.9  2.   2.1  2.2  2.3  2.4  2.5  2.6  2.7  2.8  2.9
  3.   3.1  3.2  3.3  3.4  3.5  3.6  3.7  3.8  3.9  4.   4.1  4.2  4.3  4.4
  4.5  4.6  4.7  4.8  4.9  5. ]


In [6]:
mpv=-20.
mp0=100.

mp = numpy.zeros(N)
mp[0] = mp0

m=mp0
for n in range(1,N):
    m = m + dt*mpv  
    mp[n] = m
    if t[n]>=3.15 and t[n]<=3.25 :print(m,t[n])

36.0 3.2


In [10]:
h0 = 0.  #?
v0 = 0.  #?
ms = 50.
g  = 9.81
den = 1.091
r = 0.5
A = numpy.pi*r**2
ve=325
CD=0.15

u = numpy.array([h0, v0])

h = numpy.zeros(N)
h[0] = h0 

In [34]:
u = numpy.array([h0, v0])
for n in range(1,N):
    u = u + dt*numpy.array([u[1], -g+(-mpv*ve-u[1]**2*den*A*CD/2)/(ms+mp[n])])
    h[n] = u[0]
    if h[n]-h[n-1]>=0:
        print(u,t[n])
for n in range(1,110):
    u = u + dt*numpy.array([u[1], -g-u[1]**2*den*A*CD/2/ms])
    if u[1]<=0:
        print(u,0.1*n+5)

[ 0.          3.41089189] 0.1
[ 0.34108919  6.88143458] 0.2
[  1.02923265  10.41221012] 0.3
[  2.07045366  14.00376839] 0.4
[  3.4708305   17.65662356] 0.5
[  5.23649285  21.37125031] 0.6
[  7.37361789  25.14807982] 0.7
[  9.88842587  28.9874955 ] 0.8
[ 12.78717542  32.88982851] 0.9
[ 16.07615827  36.85535289] 1.0
[ 19.76169356  40.88428061] 1.1
[ 23.85012162  44.97675612] 1.2
[ 28.34779723  49.13285077] 1.3
[ 33.26108231  53.35255685] 1.4
[ 38.59633799  57.63578135] 1.5
[ 44.35991613  61.98233939] 1.6
[ 50.55815007  66.39194738] 1.7
[ 57.1973448  70.8642158] 1.8
[ 64.28376638  75.39864173] 1.9
[ 71.82363056  79.99460099] 2.0
[ 79.82309066  84.65134007] 2.1
[ 88.28822466  89.36796764] 2.2
[ 97.22502143  94.14344586] 2.3
[ 106.63936601   98.97658139] 2.4
[ 116.53702415  103.86601607] 2.5
[ 126.92362576  108.81021748] 2.6
[ 137.80464751  113.80746915] 2.7
[ 149.18539442  118.85586071] 2.8
[ 161.0709805   123.95327781] 2.9
[ 173.46630828  129.09739194] 3.0
[ 186.37604747  134.28565026] 3.